"""add_last_logout_at_for_user

Revision ID: 0fbfd2401aba
Revises: 659a7ab07069
Create Date: 2025-11-18 19:42:08.416252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbfd2401aba'
down_revision = '659a7ab07069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_logout_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_logout_at')

    # ### end Alembic commands ###
